title: Incident Desk
description: A local desktop application for reporting and managing company incidents.
remote_theme: just-the-docs/just-the-docs@v0.12.0

plugins:
  - jekyll-remote-theme

url: https://cs3227-2610-mp2-incidentassistant.github.io
baseurl: /CS3227-2610-MP2

search_enabled: true
nav_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: Back to top
